theme: jekyll-theme-architect
title: Welcome to the Snowfairy's homepage!
description: Feel free to bookmark this to keep an eye on my blog updates

plugins:
  - jekyll-relative-links
relative_links: https://github.com/symsnowfairy/Snowfairy-Blog
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  -Learning_Note.md
  
book_filename: "Snowfairy Blog"
chapter_name: "Chapter "
repo: https://github.com/symsnowfairy/Snowfairy-Blog
output_dir: docs
rmd_files: ["index.Rmd", "Learning-Note.Rmd", "02-Getting-Unix.Rmd", "03-Command-Line-Basics.Rmd", "04-Working-with-Unix.Rmd", "05-Bash-Programming.Rmd", "06-Git-and-GitHub.Rmd", "07-Nephology.Rmd", "08-Start-Building.Rmd"]
clean: [packages.bib, bookdown.bbl]
new_session: yes
