theme: jekyll-theme-architect
title: Welcome to the Snowfairy's homepage!
description: Feel free to bookmark this to keep an eye on my blog updates

plugins:
  - jekyll-relative-links
relative_links: https://github.com/symsnowfairy/Snowfairy-Blog
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  -Learning_Note.md
