theme: jekyll-theme-architect
title: Welcome to the Snowfairy's homepage!
description: Feel free to bookmark this to keep an eye on my blog updates

  
book_filename: "Snowfairy Blog"
chapter_name: "Chapter "
repo: https://github.com/symsnowfairy/Snowfairy-Blog
output_dir: docs
rmd_files: ["index.md", "Learning_Note.md", "CONTRIBUTING.md"]
clean: [packages.bib, bookdown.bbl]
new_session: yes
